[GLOBAL]
pants_version = "2.9.0"
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black"
]

[anonymous-telemetry]
enabled=false

[source]
root_patterns = [
  '/app1',
  '/app2',
  '/lib1',
  '/lib2',
]